spring.application.name=vksonpdl-first-mcp

# Your Auth0 Tenant URL (must include trailing slash)
spring.security.jwt.issuer-uri=https://dev-x8bgd1t4j2v0rpms.us.auth0.com/
spring.security.jwt.audiences=https://vksonpdl-first-mcp.com
spring.security.jwt.resource=https://vksonpdl-first-mcp.onrender.com

# Basic Server Info
spring.ai.mcp.server.name=vksonpdl-first-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.type=sync

# Suppress console logging to protect STDIO JSON-RPC stream
#logging.pattern.console=
# Optional: redirect application logs to a file instead
#logging.file.name=logs/mcp-server.log


# Mandatory for STDIO Transport
#spring.main.web-application-type=none
#spring.main.banner-mode=off


# MCP WEBMVC Server configuration
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false
