spring.application.name=vksonpdl-first-mcp

# Basic Server Info
spring.ai.mcp.server.name=vksonpdl-first-mcp
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.type=sync

######################################
# MCP WEBMVC Server configuration
spring.ai.mcp.server.protocol=streamable
spring.ai.mcp.server.stdio=false

# Mandatory for STDIO Transport
#spring.main.web-application-type=none
#spring.main.banner-mode=off
######################################

# Your Auth0 Tenant URL (must include trailing slash)
spring.security.jwt.audiences=https://vksonpdl-first-mcp.com
spring.security.jwt.issuer-uri=https://dev-x8bgd1t4j2v0rpms.us.auth0.com/
spring.security.jwt.authorize-uri=https://dev-x8bgd1t4j2v0rpms.us.auth0.com/authorize
spring.security.jwt.token-uri=https://dev-x8bgd1t4j2v0rpms.us.auth0.com/oauth/token
spring.security.jwt.jwks-uri=https://dev-x8bgd1t4j2v0rpms.us.auth0.com/.well-known/jwks.json
#spring.security.jwt.resource=https://vksonpdl-first-mcp.onrender.com


# Suppress console logging to protect STDIO JSON-RPC stream
#logging.pattern.console=
# Optional: redirect application logs to a file instead
#logging.file.name=logs/mcp-server.log



# Hibernate Settings
# Set ddl-auto to 'validate' or 'none' since you already created tables manually
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.show_sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



